In [48]:
import matplotlib.pyplot as plt
import numpy as np
import random
import seaborn as sns
import pandas as pd

### Q. 1

In [49]:
IMDB = pd.read_csv("imdb_2019.tsv",sep="\t")

In [50]:
IMDB.head()

,index,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,87501.0,tt0089435,short,Kokoa,Kokoa,0.0,2019.0,NaN,13.0,NaN
1,89512.0,tt0091490,short,Martina's Playhouse,Martina's Playhouse,0.0,2019.0,NaN,20.0,NaN
2,114407.0,tt0116991,movie,Mariette in Ecstasy,Mariette in Ecstasy,0.0,2019.0,NaN,NaN,NaN
3,126556.0,tt0129960,tvMovie,Eine geschlossene Gesellschaft,Eine geschlossene Gesellschaft,0.0,2019.0,NaN,NaN,NaN
4,166388.0,tt0172112,short,Ambulans,Ambulans,0.0,2019.0,NaN,11.0,NaN

###  Q. 2

In [51]:
print(IMDB.titleType.value_counts())
unique =IMDB['titleType'].nunique()
print("Number Unique values:", unique)

tvEpisode       225972
short            35351
movie            15640
video            10450
tvSeries          7154
tvMovie           2431
tvMiniSeries      2000
tvSpecial         1306
videoGame          884
tvShort            151
Name: titleType, dtype: int64
Number Unique values: 10

### Q. 3

In [52]:
TPYR = IMDB.loc[:,["titleType","primaryTitle", "startYear","runtimeMinutes"]]
TPYR

,titleType,primaryTitle,startYear,runtimeMinutes
0,short,Kokoa,2019.0,13.0
1,short,Martina's Playhouse,2019.0,20.0
2,movie,Mariette in Ecstasy,2019.0,NaN
3,tvMovie,Eine geschlossene Gesellschaft,2019.0,NaN
4,short,Ambulans,2019.0,11.0
...,...,...,...,...
301334,tvEpisode,Talent Coaching with IMOR's Bianca Desmore Mit...,2019.0,NaN
301335,tvEpisode,Escape,2019.0,NaN
301336,tvEpisode,Tinne Oltmans,2019.0,NaN
301337,tvEpisode,Luc Janssens,2019.0,NaN
301338,tvEpisode,Danira Boukhriss Terkessidis,2019.0,NaN

### Q. 4

In [53]:
tvEpisodes=IMDB.loc[IMDB["titleType"]=="tvEpisode"]
tvEpisodes

,index,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
21,758955.0,tt0782666,tvEpisode,Save the Duckling!,Save the Duckling!,0.0,2019.0,NaN,NaN,NaN
30,969426.0,tt10001058,tvEpisode,Le grand saut,Le grand saut,0.0,2019.0,NaN,51.0,NaN
32,969458.0,tt10001110,tvEpisode,The Interviews,The Interviews,0.0,2019.0,NaN,NaN,NaN
34,969464.0,tt10001120,tvEpisode,The New Guy,The New Guy,0.0,2019.0,NaN,NaN,NaN
35,969465.0,tt10001122,tvEpisode,The New Girl,The New Girl,0.0,2019.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
301334,6591633.0,tt9916776,tvEpisode,Talent Coaching with IMOR's Bianca Desmore Mit...,Talent Coaching with IMOR's Bianca Desmore Mit...,0.0,2019.0,NaN,NaN,NaN
301335,6591634.0,tt9916778,tvEpisode,Escape,Escape,0.0,2019.0,NaN,NaN,NaN
301336,6591640.0,tt9916790,tvEpisode,Tinne Oltmans,Tinne Oltmans,0.0,2019.0,NaN,NaN,NaN
301337,6591646.0,tt9916802,tvEpisode,Luc Janssens,Luc Janssens,0.0,2019.0,NaN,NaN,NaN
301338,6591650.0,tt9916810,tvEpisode,Danira Boukhriss Terkessidis,Danira Boukhriss Terkessidis,0.0,2019.0,NaN,NaN,NaN

### Q. 5

In [54]:
adult = IMDB['isAdult'].mean()*100
print ("Percente adult films / total release 2019.: %s%%" % round(adult, 2))

Percente adult films / total release 2019.: 2.97%

### Q. 6

In [55]:
IMDB.isna().sum()

index                  0
tconst                 0
titleType              0
primaryTitle           1
originalTitle          1
isAdult                0
startYear              0
endYear           299192
runtimeMinutes    221511
genres            301339
dtype: int64

In [56]:
IMDB.primaryTitle.dropna()

0                                                     Kokoa
1                                       Martina's Playhouse
2                                       Mariette in Ecstasy
3                            Eine geschlossene Gesellschaft
4                                                  Ambulans
                                ...
301334    Talent Coaching with IMOR's Bianca Desmore Mit...
301335                                               Escape
301336                                        Tinne Oltmans
301337                                         Luc Janssens
301338                         Danira Boukhriss Terkessidis
Name: primaryTitle, Length: 301338, dtype: object

In [57]:
IMDB.primaryTitle.value_counts()

adult_movie_name            8945
Episode #1.1                1265
Episode #1.2                1164
Episode #1.3                1100
Episode #1.4                1009
                            ...
Kiss Burn                      1
Underground City               1
Jassie Gill: Surma Kaala       1
Suspense                       1
Purushottam                    1
Name: primaryTitle, Length: 195513, dtype: int64

In [58]:
def words_title(IMDB):
    IMDB['totalwords'] = IMDB['primaryTitle'].str.count('') + 1
words_title(IMDB)
IMDB

,index,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,totalwords
0,87501.0,tt0089435,short,Kokoa,Kokoa,0.0,2019.0,NaN,13.0,NaN,7.0
1,89512.0,tt0091490,short,Martina's Playhouse,Martina's Playhouse,0.0,2019.0,NaN,20.0,NaN,21.0
2,114407.0,tt0116991,movie,Mariette in Ecstasy,Mariette in Ecstasy,0.0,2019.0,NaN,NaN,NaN,21.0
3,126556.0,tt0129960,tvMovie,Eine geschlossene Gesellschaft,Eine geschlossene Gesellschaft,0.0,2019.0,NaN,NaN,NaN,32.0
4,166388.0,tt0172112,short,Ambulans,Ambulans,0.0,2019.0,NaN,11.0,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...
301334,6591633.0,tt9916776,tvEpisode,Talent Coaching with IMOR's Bianca Desmore Mit...,Talent Coaching with IMOR's Bianca Desmore Mit...,0.0,2019.0,NaN,NaN,NaN,95.0
301335,6591634.0,tt9916778,tvEpisode,Escape,Escape,0.0,2019.0,NaN,NaN,NaN,8.0
301336,6591640.0,tt9916790,tvEpisode,Tinne Oltmans,Tinne Oltmans,0.0,2019.0,NaN,NaN,NaN,15.0
301337,6591646.0,tt9916802,tvEpisode,Luc Janssens,Luc Janssens,0.0,2019.0,NaN,NaN,NaN,14.0
301338,6591650.0,tt9916810,tvEpisode,Danira Boukhriss Terkessidis,Danira Boukhriss Terkessidis,0.0,2019.0,NaN,NaN,NaN,30.0

### Q. 7

In [59]:
runtime = IMDB.loc[IMDB["titleType"] =="short"].runtimeMinutes.mean()
print ("Average runtimeMinutes is: %s" % round(runtime,2))

Average runtimeMinutes is: 12.54

### Q. 8

In [60]:
IMDB.loc[(IMDB["titleType"]=="tvMovie") 
         & (IMDB["totalwords"]>=3) 
         & (IMDB["runtimeMinutes"]< 75)]

,index,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,totalwords
10,290068.0,tt0302617,tvMovie,Great Bear Rainforest,Great Bear Rainforest,0.0,2019.0,NaN,41.0,NaN,23.0
77,970092.0,tt10002188,tvMovie,"La Sagi, una pionera del BarÃ§a","La Sagi, una pionera del BarÃ§a",0.0,2019.0,NaN,54.0,NaN,32.0
655,972490.0,tt10006422,tvMovie,Warrior Women of Dahomey,Warrior Women of Dahomey,0.0,2019.0,NaN,60.0,NaN,26.0
870,974152.0,tt10009314,tvMovie,Peter Kraus: Immer in Bewegung,Peter Kraus: Immer in Bewegung,0.0,2019.0,NaN,59.0,NaN,32.0
1549,977406.0,tt10015036,tvMovie,Arts Across the Heartland,Arts Across the Heartland,0.0,2019.0,NaN,42.0,NaN,27.0
...,...,...,...,...,...,...,...,...,...,...,...
300451,6587871.0,tt9908916,tvMovie,Restless Legs Syndrome: The New Cure?,Restless Legs Syndrome: The New Cure?,0.0,2019.0,NaN,60.0,NaN,39.0
300975,6590161.0,tt9913680,tvMovie,Olympiad drÃ¶mmen 2020,Olympiad drÃ¶mmen 2020,0.0,2019.0,NaN,27.0,NaN,23.0
301155,6591048.0,tt9915520,tvMovie,Fascism i en svart bil,Fascism i en svart bil,0.0,2019.0,NaN,55.0,NaN,24.0
301240,6591316.0,tt9916112,tvMovie,"A Priest, a Rabbi, and a Nun walk into a...","A Priest, a Rabbi, and a Nun walk into a...",0.0,2019.0,NaN,21.0,NaN,45.0
301247,6591353.0,tt9916192,tvMovie,Danielle Darrieux: Il est poli d'Ãªtre gai!,Danielle Darrieux: Il est poli d'Ãªtre gai!,0.0,2019.0,NaN,53.0,NaN,44.0